{
 "title": "Cellular Dashboard - Provider A",
 "time": { "from": "2023-04-25T06:37:00.000Z", "to": "2023-04-25T07:40:00.000Z" },
 "panels": [
  {
   "title": "Cellular RSSI - Received Signal Strength Indication (in dBm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_radio",
     "select": [
      [
       { "params": [ "radio_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cellular_interface", "operator": "=", "value": "Cellular0/1/0" }
     ]
    }
   ]
  },
  {
   "title": "Signal-to-Noise Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_radio",
     "select": [
      [
       { "params": [ "radio_snr" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "405ba7def0bd" }
     ]
    }
   ]
  },
  {
   "title": "Cellular RSRP - Reference Signal Received Power (in dBm)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_radio",
     "select": [
      [
       { "params": [ "radio_rsrp" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cellular_interface", "operator": "=", "value": "Cellular0/1/0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "405ba7def0bd" }
     ]
    }
   ]
  },
  {
   "title": "Cellular RSRQ - Reference Signal Received Quality (in dB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_radio",
     "select": [
      [
       { "params": [ "radio_rsrq" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cellular_interface", "operator": "=", "value": "Cellular0/1/0" },
      { "condition": "AND", "key": "host", "operator": "=", "value": "405ba7def0bd" }
     ]
    }
   ]
  },
  {
   "title": "Receiver Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_connection",
     "select": [
      [
       { "params": [ "rx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_connection",
     "select": [
      [
       { "params": [ "tx_packets" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cellular Packet Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_connection",
     "select": [
      [
       { "params": [ "cellular_packet_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Signal Service Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_network",
     "select": [
      [
       { "params": [ "current_service_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Modem temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_hardware",
     "select": [
      [
       { "params": [ "cellular_modem_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cellular Tech. Selection",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_radio",
     "select": [
      [
       { "params": [ "radio_rat_selected" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Modem Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cell_hardware",
     "select": [
      [
       { "params": [ "cellular_modem_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}